POST  http://localhost:5000/signup
Content-Type: application/json

{
    "username": "poppy10",
    "password": "1234567",
    "email": "poppy10@gmail.com"
}

###
POST http://panda-pay.herokuapp.com/login
Content-Type: application/json

{
    "email": "king@gmail.com",
    "password": "1234566"
}

###
GET http://panda-pay.herokuapp.com/user
Content-Type: application/json

{
    "id": "623b5be40ab17b35af2265d5"
}

###
GET http://localhost:5000/users
