POST  http://localhost:5000/signup
Content-Type: application/json

{
    "username": "mark",
    "password": "1234567",
    "email": "mark@gmail.com"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "kinng@gmail.com",
    "password": "1234567"
}

###
GET http://localhost:5000/users
