GET http://localhost:3000/users

###
POST http://localhost:5000/sendmessage
Content-Type: application/json

{
    "name": "Mark",
    "password": "1234567"
}

###
GET https://pandamailingservice.herokuapp.com/msg